# Optics preset for Week-2
wavelength_nm:
- 300
- 320
- 340
- 360
- 380
- 400
- 420
- 440
- 460
- 480
- 500
- 520
- 540
- 560
- 580
- 600
water:
  RINDEX:
  - 1.3435
  - 1.3415
  - 1.3399
  - 1.3385
  - 1.3373
  - 1.3362
  - 1.3353
  - 1.3345
  - 1.3338
  - 1.3333
  - 1.3328
  - 1.3323
  - 1.3319
  - 1.3315
  - 1.3312
  - 1.331
  ABSLENGTH:
  - 5e3
  - 1e4
  - 2e4
  - 3e4
  - 5e4
  - 7e4
  - 8e4
  - 9e4
  - 1e5
  - 9e4
  - 8e4
  - 6e4
  - 4e4
  - 3e4
  - 2e4
  - 1.5e4
  RAYLEIGH:
  - 3.5e4
  - 4.5e4
  - 5.6e4
  - 7.0e4
  - 8.3e4
  - 9.0e4
  - 1.1e5
  - 1.3e5
  - 1.55e5
  - 1.8e5
  - 2.1e5
  - 2.4e5
  - 2.75e5
  - 3.1e5
  - 3.5e5
  - 3.9e5
surfaces:
  wall:
    type: dielectric_metal
    model: unified
    finish: ground
    sigma_alpha: 0.1
    REFLECTIVITY:
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
    - 0.02
  photocathode:
    type: dielectric_dielectric
    model: unified
    finish: polished
    EFFICIENCY:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    REFLECTIVITY:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
